// Generated by gencpp from file gopigo3_node/SPI.msg
// DO NOT EDIT!


#ifndef GOPIGO3_NODE_MESSAGE_SPI_H
#define GOPIGO3_NODE_MESSAGE_SPI_H

#include <ros/service_traits.h>


#include <gopigo3_node/SPIRequest.h>
#include <gopigo3_node/SPIResponse.h>


namespace gopigo3_node
{

struct SPI
{

typedef SPIRequest Request;
typedef SPIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SPI
} // namespace gopigo3_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gopigo3_node::SPI > {
  static const char* value()
  {
    return "e04010cc40eb2ab4db306dc8c290e92b";
  }

  static const char* value(const ::gopigo3_node::SPI&) { return value(); }
};

template<>
struct DataType< ::gopigo3_node::SPI > {
  static const char* value()
  {
    return "gopigo3_node/SPI";
  }

  static const char* value(const ::gopigo3_node::SPI&) { return value(); }
};


// service_traits::MD5Sum< ::gopigo3_node::SPIRequest> should match
// service_traits::MD5Sum< ::gopigo3_node::SPI >
template<>
struct MD5Sum< ::gopigo3_node::SPIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gopigo3_node::SPI >::value();
  }
  static const char* value(const ::gopigo3_node::SPIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gopigo3_node::SPIRequest> should match
// service_traits::DataType< ::gopigo3_node::SPI >
template<>
struct DataType< ::gopigo3_node::SPIRequest>
{
  static const char* value()
  {
    return DataType< ::gopigo3_node::SPI >::value();
  }
  static const char* value(const ::gopigo3_node::SPIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gopigo3_node::SPIResponse> should match
// service_traits::MD5Sum< ::gopigo3_node::SPI >
template<>
struct MD5Sum< ::gopigo3_node::SPIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gopigo3_node::SPI >::value();
  }
  static const char* value(const ::gopigo3_node::SPIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gopigo3_node::SPIResponse> should match
// service_traits::DataType< ::gopigo3_node::SPI >
template<>
struct DataType< ::gopigo3_node::SPIResponse>
{
  static const char* value()
  {
    return DataType< ::gopigo3_node::SPI >::value();
  }
  static const char* value(const ::gopigo3_node::SPIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GOPIGO3_NODE_MESSAGE_SPI_H
